pokemons = [
  {
    name: "Bulbasaur",
    number: 1,
    male: true,
    description: "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokemon.",
    hp: 45,
    atk: 49,
    def: 49,
    spatk: 65,
    spdef: 65,
    spd: 45,
    tot: 318,
    height: 0.7,
    weight: 6.9,
    image_url: "https://img.pokemondb.net/sprites/x-y/normal/bulbasaur.png"
  },
  {
    name: "Ivysaur",
    number: 2,
    male: true,
    description: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.",
    hp: 60,
    atk: 62,
    def: 63,
    spatk: 80,
    spdef: 80,
    spd: 60,
    tot: 405,
    height: 1.0,
    weight: 13.0,
    image_url: "https://img.pokemondb.net/sprites/x-y/normal/ivysaur.png"
  },
  {
    name: "Venusaur",
    number: 3,
    male: true,
    description: "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
    hp: 80,
    atk: 82,
    def: 83,
    spatk: 100,
    spdef: 100,
    spd: 80,
    tot: 525,
    height: 2.0,
    weight: 100.0,
    image_url: "https://img.pokemondb.net/sprites/x-y/normal/venusaur.png"
  },
  {
    name: "Charmander",
    number: 4,
    male: true,
    description: "From the time it is born, a flame burns at the tip of its tail. Its life would end if the flame were to go out.",
    hp: 39,
    atk: 52,
    def: 43,
    spatk: 60,
    spdef: 50,
    spd: 65,
    tot: 309,
    height: 0.6,
    weight: 8.5,
    image_url: "https://img.pokemondb.net/sprites/x-y/normal/charmander.png"
  },
  {
    name: "Charmeleon",
    number: 5,
    male: true,
    description: "When it swings its burning tail, it elevates the temperature to unbearably high levels.",
    hp: 58,
    atk: 64,
    def: 58,
    spatk: 80,
    spdef: 65,
    spd: 80,
    tot: 405,
    height: 1.1,
    weight: 19.0,
    image_url: "https://img.pokemondb.net/sprites/x-y/normal/charmeleon.png"
  },
  {
    name: "Charizard",
    number: 6,
    male: true,
    description: "It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.",
    hp: 78,
    atk: 84,
    def: 78,
    spatk: 109,
    spdef: 85,
    spd: 100,
    tot: 534,
    height: 1.7,
    weight: 90.5,
    image_url: "https://img.pokemondb.net/sprites/x-y/normal/charizard.png"
  },
  {
    name: "Squirtle",
    number: 7,
    male: true,
    description: "When it retracts its long neck into its shell, it squirts out water with vigorous force.",
    hp: 44,
    atk: 48,
    def: 65,
    spatk: 50,
    spdef: 64,
    spd: 43,
    tot: 314,
    height: 0.5,
    weight: 9.0,
    image_url: "https://img.pokemondb.net/sprites/x-y/normal/squirtle.png"
  },
  {
    name: "Wartortle",
    number: 8,
    male: true,
    description: "It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old.",
    hp: 59,
    atk: 63,
    def: 80,
    spatk: 65,
    spdef: 80,
    spd: 58,
    tot: 405,
    height: 1.0,
    weight: 22.5,
    image_url: "https://img.pokemondb.net/sprites/x-y/normal/wartortle.png"
  },
  {
    name: "Blastoise",
    number: 9,
    male: true,
    description: "It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.",
    hp: 79,
    atk: 83,
    def: 100,
    spatk: 85,
    spdef: 105,
    spd: 78,
    tot: 530,
    height: 1.6,
    weight: 85.5,
    image_url: "https://img.pokemondb.net/sprites/x-y/normal/blastoise.png"
  },
  {
    name: "Caterpie",
    number: 10,
    male: true,
    description: "For protection, it releases a horrible stench from the antenna on its head to drive away enemies.",
    hp: 45,
    atk: 30,
    def: 35,
    spatk: 20,
    spdef: 20,
    spd: 45,
    tot: 195,
    height: 0.3,
    weight: 2.9,
    image_url: "https://img.pokemondb.net/sprites/x-y/normal/caterpie.png"
  },
  {
    name: "Pikachu",
    number: 25,
    male: true,
    description: "It stores electricity in the electric sacs on its cheeks. When it releases pent-up energy in a burst, the electric power is equal to a lightning bolt.",
    hp: 35,
    atk: 55,
    def: 40,
    spatk: 50,
    spdef: 50,
    spd: 90,
    tot: 320,
    height: 0.4,
    weight: 6.0,
    image_url: "https://img.pokemondb.net/sprites/x-y/normal/pikachu.png"
  }
]

# Clear existing Pokemon data
Pokemon.destroy_all

# Insert the new Pokemon data
pokemons.each do |pokemon_data|
  Pokemon.create!(pokemon_data)
end